### ISSUE TITLE
get-qliktask where enabled and status is failed

### ISSUE THREAD

**Issue by SQLJames** [ahaydon/Qlik-Cli#15]
The result from operational Lastexecutionresult from the get-qliktask when using the -full parameter doesn't return the right value. 
This also happens on the get-qlikreloadtask 

As a work around, i was able to get the items i needed using this 

$GetfailedTasks=(Get-QlikTask | where {$_.status -eq 'FinishedFail'}).name
$getfailedenabledTasks=Get-QlikTask -full | where { $_.enabled -eq 'True' } | where {$_.name -in $GetfailedTasks} |Select name 
 Foreach ($task in $getfailedenabledTasks) {
 Start-QlikTask $task.name
 }

**Comment by ahaydon** [comment]
As the operational lastexecutionresult is a property of the task that is returned from a single API call, if the result is incorrect it would suggest an issue in the Sense API rather than this module. The following command should get the same result as your code.
Get-QlikTask -filter "operational.lastExecutionResult.status eq FinishedFail and enabled eq true" -raw | Start-QlikTask
