### ISSUE TITLE
Receiving 401 Unauthorized Errors upon Connect

### ISSUE THREAD

**Issue by patrick-ryan1** [ahaydon/Qlik-Cli#33]
Running 

`Connect-Qlik -Computername "central node" -Credential <domain\id>
`
Results in a 401 Unauthorized error. 

Using  

`Connect-Qlik -Computername "central node" -UseDefaultCredentials 
`
when logged into server works.

I have also tried the following and can see the TLS1.2 is being used:

```
$req = New-Object System.Net.WebClient 
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Connect-Qlik -computername Connect-Qlik -Computername "central node" -Credential <domain\id>
```

(From Fiddler log)
Secure Protocol: Tls12
Cipher: Aes256 256bits
Hash Algorithm: Sha384 384bits
Key Exchange: ECDHE_RSA (0xae06) 256bits

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.
Version: 3.3 (TLS/1.2)

Connect is via Windows Authentication port on server 4244.

Also, testing with curl is working with this command:

`curl -v -L --ntlm --negotiate -u : --insecure "central node" /qrs/app?xrfkey=0123456789abcdef --header "x-qlik-xrfkey: 0123456789abcdef" --header "User-Agent: Windows"
`

Any ideas on how to solve?  

Regards

**Comment by patrick-ryan1** [comment]
Also, testing with curl is working with this command:

curl -v -L --ntlm --negotiate -u : --insecure <central node>/qrs/app?xrfkey=0123456789abcdef --header "x-qlik-xrfkey: 0123456789abcdef" --header "User-Agent: Windows"

However am not required to login this method as it is using current login.

**Comment by ahaydon** [comment]
The module uses the Invoke-RestMethod cmdlet to connect to Sense, and the Credential parameter is passed directly to that command. Even when using that cmdlet without Qlik-Cli it still fails to pass the credentials to Sense, so this seems to be a PowerShell issue rather than a bug with this module.
If it works using the WebClient class then it would be possible to updte the module to use that rather than the cmdlet and this could solve the problem.

**Comment by ahaydon** [comment]
Credential option has now been removed
